### ISSUE TITLE
poprawki css/html

### ISSUE THREAD

**Issue by michal-bootcamp** [JoannaKu/lets-tweet#1]
- [x] dolaczaj fonty z googla wraz z grubosciami, ktorych uzywasz (jesli grubosci sa inne niz domyslne 400 - normal)
- [x] dodaj fallbacki do fontow np `font-family: 'Source Code Pro', monospace;`
- [x] ta regula nic nie robi i jest niepotrzebna:
```
a {
    list-style-type: none;
}
```
- [x] pokoloruj link do twittera w taki sam sposob jak pierwszy button i usun podkreslenie linka
- [x] niech na calych buttonach kursor zmienia sie na "łapkę"
- [x] dodaj meta viewport, zeby strona lepiej wygladala pod mobile
- [x] `0px` -> `0`

**Comment by JoannaKu** [comment]
1. wszędzie używam tylko grubości 400, czyli nie dołączać?

**Comment by michal-bootcamp** [comment]
1. jestes pewna? :) https://scr.hu/PKKPVn
Widze, ze font Pacifico nie ma grubosci 700 na google fonts, wiec niech bedzie pogrubiany przez przegladarke, ale Source Code Pro juz ma taka grubosc dostepna
